[project]
name = "plotnine-org"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "geodatasets>=2024.8.0",
    "plotnine[doc,extra]>=0.14.5",
]
