---
title: Facet wrap
jupyter: python3
---

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:50.157636Z', iopub.status.busy: '2024-03-05T11:27:50.157338Z', iopub.status.idle: '2024-03-05T11:27:50.862578Z', shell.execute_reply: '2024-03-05T11:27:50.861839Z'}

from plotnine import ggplot, aes, geom_point, labs, facet_wrap, theme
from plotnine.data import mpg
```


`facet_wrap()` creates a collection of plots (facets), where each plot is differentiated by the faceting variable. These plots are wrapped into a certain number of columns or rows as specified by the user.


```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:50.865808Z', iopub.status.busy: '2024-03-05T11:27:50.865562Z', iopub.status.idle: '2024-03-05T11:27:50.879202Z', shell.execute_reply: '2024-03-05T11:27:50.878617Z'}
mpg.head()
```

Basic scatter plot:

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:50.919007Z', iopub.status.busy: '2024-03-05T11:27:50.918743Z', iopub.status.idle: '2024-03-05T11:27:52.054424Z', shell.execute_reply: '2024-03-05T11:27:52.053744Z'}
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + labs(x="displacement", y="horsepower")
)
```

Facet a discrete variable using `facet_wrap()`:

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:52.058029Z', iopub.status.busy: '2024-03-05T11:27:52.057648Z', iopub.status.idle: '2024-03-05T11:27:52.745764Z', shell.execute_reply: '2024-03-05T11:27:52.745253Z'}
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap("class")
    + labs(x="displacement", y="horsepower")
)
```

Control the number of rows and columns with the options `nrow` and `ncol`:

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:52.748541Z', iopub.status.busy: '2024-03-05T11:27:52.748311Z', iopub.status.idle: '2024-03-05T11:27:53.546363Z', shell.execute_reply: '2024-03-05T11:27:53.545846Z'}
# Selecting the number of columns to display
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap(
        "class",
        ncol=4,  # change the number of columns
    )
    + labs(x="displacement", y="horsepower")
)
```

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:53.548976Z', iopub.status.busy: '2024-03-05T11:27:53.548742Z', iopub.status.idle: '2024-03-05T11:27:54.200245Z', shell.execute_reply: '2024-03-05T11:27:54.199707Z'}
# Selecting the number of rows to display

(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap(
        "class",
        nrow=4,  # change the number of columns
    )
    + labs(x="displacement", y="horsepower")
)
```

To change the plot order of the facets, reorder the levels of the faceting variable in the data.

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:54.204094Z', iopub.status.busy: '2024-03-05T11:27:54.203836Z', iopub.status.idle: '2024-03-05T11:27:54.207956Z', shell.execute_reply: '2024-03-05T11:27:54.207437Z'}
# re-order categories
mpg["class"] = mpg["class"].cat.reorder_categories(
    ["pickup", "suv", "minivan", "midsize", "compact", "subcompact", "2seater"]
)
```

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:54.210974Z', iopub.status.busy: '2024-03-05T11:27:54.210713Z', iopub.status.idle: '2024-03-05T11:27:54.887959Z', shell.execute_reply: '2024-03-05T11:27:54.887406Z'}
# facet plot with reorded drv category
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap("class")
    + labs(x="displacement", y="horsepower")
)
```

Ordinarily the facets are arranged horizontally (left-to-right from top to bottom). However if you would prefer a vertical layout (facets are arranged top-to-bottom, from left to right) use the `dir` option:

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:54.890970Z', iopub.status.busy: '2024-03-05T11:27:54.890734Z', iopub.status.idle: '2024-03-05T11:27:55.704944Z', shell.execute_reply: '2024-03-05T11:27:55.704298Z'}
# Facet plot with vertical layout
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap(
        "class",
        dir="v",  # change to a vertical layout
    )
    + labs(x="displacement", y="horsepower")
)
```

You can choose if the scale of x- and y-axes are fixed or variable. Set the `scales` argument to `free-y`, `free_x` or `free` for a free scales on the y-axis, x-axis or both axes respectively. You may need to add spacing between the facets to ensure axis ticks and values are easy to read.

A fixed scale is the default and does not need to be specified.

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:55.707756Z', iopub.status.busy: '2024-03-05T11:27:55.707495Z', iopub.status.idle: '2024-03-05T11:27:56.492420Z', shell.execute_reply: '2024-03-05T11:27:56.491814Z'}
# facet plot with free scales
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap(
        "class",
        scales="free_y",  # set scales so y-scale varies with the data
    )
    + labs(x="displacement", y="horsepower")
)
```

You can add additional information to your facet labels, by using the `labeller` argument within the `facet_wrap()` command. Below we use `labeller = 'label_both'` to include the column name in the facet label.

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:56.495363Z', iopub.status.busy: '2024-03-05T11:27:56.495129Z', iopub.status.idle: '2024-03-05T11:27:57.318086Z', shell.execute_reply: '2024-03-05T11:27:57.317545Z'}
# facet plot with labeller
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap("class", labeller="label_both")
    + labs(x="displacement", y="horsepower")
)
```

You can add two discrete variables to a facet:

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:57.321708Z', iopub.status.busy: '2024-03-05T11:27:57.321486Z', iopub.status.idle: '2024-03-05T11:27:57.325318Z', shell.execute_reply: '2024-03-05T11:27:57.324807Z'}
# add additional column for plotting exercise
mpg["transmission"] = mpg["trans"].map(
    lambda x: "auto" if "auto" in x else "man" if "man" in x else ""
)
```

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:57.328227Z', iopub.status.busy: '2024-03-05T11:27:57.328008Z', iopub.status.idle: '2024-03-05T11:27:57.337513Z', shell.execute_reply: '2024-03-05T11:27:57.337042Z'}
# inspect new column transmission which identifies cars as having an automatic or manual transmission
mpg.head()
```

```{python}
#| execution: {iopub.execute_input: '2024-03-05T11:27:57.340109Z', iopub.status.busy: '2024-03-05T11:27:57.339914Z', iopub.status.idle: '2024-03-05T11:27:58.382185Z', shell.execute_reply: '2024-03-05T11:27:58.381606Z'}
# facet plot with two variables on one facet
(
    ggplot(mpg, aes(x="displ", y="hwy"))
    + geom_point()
    + facet_wrap(["class", "transmission"])  # use a list to add additional facetting variables
    + labs(x="displacement", y="horsepower")
)
```

