project:
  type: website
  preview:
    port: 11300
  output-dir: _site
  resources:
    - objects.inv
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!plotnine"
    - "!plotnine-examples"

website:
  title: "plotnine {{< var version >}}"
  open-graph: true
  site-url: https://plotnine.org
  favicon: "images/favicon-32x32.png"
  page-navigation: true
  navbar:
    left:
      - file: reference/index.qmd
        text: "Reference"
      - file: gallery/index.qmd
      - text: Blog
        file: blog.qmd
      - file: tutorials/index.qmd
      - text: "Pages"
        menu:
          - changelog.qmd
          - external-resources.qmd
          - about.qmd
    right:
      - icon: github
        href: https://github.com/has2k1/plotnine
  page-footer:
    left: |
      Proudly supported by
      [![](/images/posit-logo.svg){fig-alt="Posit" width=65px}](https://posit.co)

    center: |
      Developed by: Hassan Kibirige,
      License: [MIT](/license.html)

format:
  html:
    toc: true
    theme:
      - lumen
      - qrenderer.scss
      - plotnine.scss
      - website.scss
    include-in-header:
      - text: |
          <script defer data-domain="plotnine.org" src="https://plausible.io/js/script.js"></script>

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    matplotlib:
      url: https://matplotlib.org/stable/
    mizani:
      url: https://mizani.readthedocs.io/en/stable/
    numpy:
      url: https://numpy.org/doc/stable/
    scipy:
      url: https://docs.scipy.org/doc/scipy/
    statsmodels:
      url: https://www.statsmodels.org/stable/
    pandas:
      url: https://pandas.pydata.org/pandas-docs/stable/
    sklearn:
      url: https://scikit-learn.org/stable/
    skmisc:
      url: https://has2k1.github.io/scikit-misc/stable/
    adjustText:
      url: https://adjusttext.readthedocs.io/en/latest/
    patsy:
      url: https://patsy.readthedocs.io/en/stable/

issuey:
  issue-url: "https://github.com/has2k1/plotnine/issues/%id"
  issue-text: "#%id"
  issue-title: "Issue: #%id"
  pull-request-url: "https://github.com/has2k1/plotnine/pulls/%id"
  pull-request-text: "PR%id"
  pull-request-title: "Pull Request: #%id"
