name: Website

on:
  push:
    branches:
      - main

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      plotnine-doc-version: stable
      deploy-branch: stable

