name: Build Site

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      deploy-branch:
        description: "The branch to deploy the built documentations"
        default: gh-pages
        type: string
        required: true
      plotnine-doc-version:
        # one of (stable, latest, dev)
        description: "What plotnine API docs to checkout and build"
        default: stable
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Checkout Plotnine  Version
        shell: bash
        run: |
          make checkout-${{ inputs.plotnine-doc-version }}
          pushd plotnine; echo $(git tag -l --contains HEAD | head -n 1); popd

      - name: Install Dependencies
        shell: bash
        run: |
          make site-cold

      - name: Environment Information
        shell: bash
        run: |
          ls -la

      - name: Deploy Documentation to a Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: ${{ inputs.deploy-branch }}
          commit-message: ${{ github.event.head_commit.message }}
