name: Build Site

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-folder:
        description: "The folder to deploy the built documentation"
        default: ""
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release

      - name: Checkout Plotnine
        shell: bash
        run: |
          make checkout-stable
          pushd plotnine; echo $(git tag -l --contains HEAD | head -n 1); popd

      - name: Build Site
        shell: bash
        run: |
          make site-cold
          make redirects

      - name: Environment Information
        shell: bash
        run: |
          ls -la

      - name: Deploy Documentation to a Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          commit-message: ${{ github.event.head_commit.message }}
          clean-exclude:
            - CNAME
            - en
          target_folder: ${{ inputs.target-folder }}
