name: Build Site

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-folder:
        description: |
          The folder on gh-pages where to deploy the built documentation.
          If it is an empty string, the documentation is not deployed but
          it is uploaded as an artifact named _site.
        default: "."
        type: string
        required: true
      plotnine-branch:
        # one of: release, main, dev
        # "release" checks out the latest version
        description: "The branch to checkout"
        default: release
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.8.2

      # https://github.com/marketplace/actions/setup-ffmpeg
      - uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Checkout Plotnine
        shell: bash
        run: |
          make checkout-${{ inputs.plotnine-branch }}
          pushd plotnine; echo $(git tag -l --contains HEAD | head -n 1); popd

      - name: Build Site
        shell: bash
        run: |
          make site-cold

      - name: Environment Information
        shell: bash
        run: |
          ls -la

      - name: Upload Artifacts of the Built Documentation
        if: ${{ inputs.target-folder == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: source/_site
          retention-days: 1

      - name: Deploy Documentation to a Branch
        if: ${{ inputs.target-folder != '' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: source/_site
          branch: gh-pages
          target-folder: ${{ inputs.target-folder }}
          commit-message: ${{ github.event.head_commit.message }}
          clean-exclude: |
            CNAME
            en
            dev
            webdev
