name: Build Website - Dev

on:
  repository_dispatch:
    types: [plotnine-pre-release]
  workflow_dispatch:

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      plotnine-branch: pre-release
      target-folder: dev
