name: Website

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      # TODO: Change version to stable after the next release
      plotnine-doc-version: latest
      deploy-branch: gh-pages
