name: Build Site

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-folder:
        description: "The folder to deploy the built documentation"
        default: "."
        type: string
        required: true
      plotnine-branch:
        # one of: release, main, dev
        # "release" checks out the latest version
        description: "The branch to checkout"
        default: release
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.33

      - name: Checkout Plotnine
        shell: bash
        run: |
          make checkout-${{ inputs.plotnine-branch }}
          pushd plotnine; echo $(git tag -l --contains HEAD | head -n 1); popd

      - name: Build Site
        shell: bash
        run: |
          make site-cold

      - name: Environment Information
        shell: bash
        run: |
          ls -la

      - name: Deploy Documentation to a Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          target-folder: ${{ inputs.target-folder }}
          commit-message: ${{ github.event.head_commit.message }}
          clean-exclude: |
            CNAME
            en
            dev
            webdev
