name: Build Website - Web Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      plotnine-branch: main
      target-folder: webdev
