name: Github Pages

on:
  push:
    branches:
      - dev

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      # eventually doc-version should be stable
      plotnine-doc-version: dev
      deploy-branch: gh-pages
