name: Build Website - Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      plotnine-branch: release
      target-folder: "--pr-${{github.event_name}}"
